"""Agent Harness Protocol public API."""

from .compatibility import (
    COMPATIBLE,
    CompatibilityIssue,
    CompatibilityIssueKind,
    CompatibilityReport,
    CompatibilityStatus,
    HarnessTransportError,
    IncompatibleRequirementError,
    InteractionResponseUnconfirmedError,
    RequirementUnconfirmedError,
    SessionBlockedError,
    TaskStartUnconfirmedError,
    UnconfirmedResponse,
    UnconfirmedStart,
)
from .diagnostics import DiagnosticEvent, DiagnosticGap, ProviderDiagnostic, TaskDiagnostics
from .events import (
    EffectChanged,
    InteractionRequested,
    InteractionResolved,
    MessageCompleted,
    MessageDelta,
    MessageRole,
    ObservationGap,
    TaskCancelled,
    TaskCompleted,
    TaskEvent,
    TaskFailed,
    TaskStarted,
    TaskState,
    TaskUnresolved,
    TerminalEvent,
    ToolCallChanged,
    UsageChanged,
    Warning,
    WarningKind,
    WorkStatus,
)
from .harness import (
    AgentHarness,
    AgentSession,
    AgentTask,
    ContextRetentionDisposition,
    PersistentSessions,
    SessionDisposition,
    UserHistoryVisibility,
)
from .identity import (
    ApprovalScopeId,
    InteractionId,
    MessageId,
    PersistentSessionRef,
    ProviderId,
    SessionId,
    StorageNamespace,
    TaskId,
    WorkId,
)
from .interaction import (
    AnswerResponse,
    ApprovalDecision,
    ApprovalRequest,
    ApprovalResponse,
    Cleared,
    ClearReason,
    EffectKind,
    InteractionRequest,
    InteractionResolution,
    InteractionResponse,
    QuestionRequest,
    Responded,
    SessionApprovalGrant,
)
from .outcome import (
    AgentUsage,
    Cancelled,
    Completed,
    Failed,
    FailureKind,
    SchemaValidation,
    StopReason,
    StructuredOutput,
    TaskOutcome,
    TaskOutput,
    TextOutput,
    Unresolved,
    UnresolvedReason,
)
from .requirements import (
    FULL_ACCESS,
    READ_ONLY,
    TEXT_OUTPUT,
    ApprovalRequirement,
    ContextRetentionRequirement,
    DiagnosticsRequirement,
    ExecutionConstraint,
    FilesystemAccess,
    FullAccess,
    NetworkAccess,
    OutputRequirement,
    PersistenceRequirement,
    QuestionRequirement,
    ReadOnly,
    SessionRequirements,
    SessionSpec,
    SkillReference,
    StructuredOutputRequirement,
    TaskInput,
    TaskRequest,
    TaskRequirements,
    TextInput,
    TextOutputRequirement,
    UserHistoryVisibilityRequirement,
    WorkspaceRequirement,
    WorkspaceWrite,
)
from .support import (
    SUPPORTED,
    Capability,
    CleanupBudget,
    ConditionalSupport,
    Support,
    Supported,
    SupportReport,
    SupportScope,
    UnknownSupport,
    Unsupported,
)

__version__ = "0.2.3"

__all__ = [name for name in globals() if not name.startswith("_")]
